#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/types.h>


#define N_NEWSTEAMS 10 
#define EXAMPLE_NEWS 5 
#define NEWS_MAX_SIZE 512 
int main_pid; 
int pipes [N_NEWSTEAMS][2]; 
// Just some news used as an example 
char example_news[EXAMPLE_NEWS][NEWS_MAX_SIZE] = { "all about the money", "food for the soul", "home team wins", "an amazing discovery", "newest tec came out" };


// News structure that will be used to send news through the pipes 
typedef struct _news { 
    int team; 
    char newsText[NEWS_MAX_SIZE]; 
} news; 

news news_data; 

// Treatment of signal generated by Ctrl+C 
// Editor waits for all the NEWSTEAMS to finish and removes resources (closes all open // pipes); 
//NEWSTEAMS clean used resources (close all open pipes). 
//Each process prints a // message to the screen (see example output)
void sigint(int signum) {
    if(getpid() == main_pid){
        for (int i = 0; i < N_NEWSTEAMS; i++) wait(NULL);
        printf("^C Pressed. Editor shutting down\n");
    }
    else printf("^C Pressed. Shutting down news team %d.\n", news_data.team);
    
    for (int i = 0; i < N_NEWSTEAMS; i++){
        close(pipes[i][0]);
        close(pipes[i][1]);
    }
    exit(0);
}

// Code run by NEWSTEAMS 
void newsTeam(int channel[], int i){ 
    news_data.team = i; 
    srand(i); 
    // *** COMPLETE: Handle CTRL-C *** 
    signal(SIGINT, sigint);
    // *** END COMPLETE *** 
    while(1){ //pick a random news content 
        strcpy(news_data.newsText , example_news[rand() % EXAMPLE_NEWS]); 
        printf("News team %d Submitting news: \"%s\" \n", news_data.team, news_data.newsText); 
        // *** COMPLETE: Send news to pipe and sleep between 1 to 3 seconds *** 
        write(channel[1], news_data.newsText, strlen(news_data.newsText) +1);
        sleep(rand() % 3 + 1);
        // *** END COMPLETE *** 
    } 
}


int main(){
    main_pid = getpid();
    //Ignorar o sinal
    signal(SIGINT, SIG_IGN);
    
    //Criação de Pipes
    for (int i = 0; i < N_NEWSTEAMS; i++){
        if(pipe(pipes[i]) == -1){
            perror("Erro a criar pipes");
            exit(0);
        }
    }
    //Criação de processos
    for (int i = 0; i < N_NEWSTEAMS; i++){
        if(fork() == 0){
            newsTeam(pipes[i], i);
        }
    }

    fd_set read_set;
    int r;

    //Handle cntr c
    signal(SIGINT, sigint);
    
    while(1){
        FD_ZERO(&read_set);
        for (int i = 0; i < N_NEWSTEAMS; i++){
            FD_SET(pipes[i][0], &read_set);
        }
        if(select(pipes[N_NEWSTEAMS-1][0]+1, &read_set, NULL, NULL, NULL) > 0){
            char new_str[NEWS_MAX_SIZE];
            for (int i = 0; i < N_NEWSTEAMS; i++){
                if(FD_ISSET(pipes[i][0], &read_set)){
                    r = read(pipes[i][0],new_str, sizeof(new_str));
                    new_str[r-1] = '\0';
                    int publish = rand() % 100 +1;
                    if(publish <= 10) printf("NEWS FLASH: Team [%d]: %s\n", i, new_str);
                }
            }
        }
    }
}




